100
OS_RET_CODE_OK#~Sep@#Ok#~Sep@#了解
OS_RET_CODE_ERROR#~Sep@#Unrecognizable error #~Sep@#不明なｴﾗｰです
OS_RET_CODE_NOT_EXIT#~Sep@#No such file or directory#~Sep@#指定されたﾌｧｲﾙまたはﾃﾞｨﾚｸﾄﾘが存在しません
OS_RET_CODE_PARAM_ILLIGAL#~Sep@#Illegal parameter#~Sep@#ﾊﾟﾗﾒｰﾀが不正です
OS_RET_CODE_BAD_DRIVE#~Sep@#Bad drive name#~Sep@#ﾄﾞﾗｲﾌﾞ名が不正です
OS_RET_CODE_DELETE_FAIL#~Sep@#Delete operation failed#~Sep@#削除操作が失敗しました
OS_RET_CODE_OPEN_FAIL#~Sep@#Open operation failed#~Sep@#開けませんでした
OS_RET_CODE_WRITE_ERR#~Sep@#Write error#~Sep@#書き込みｴﾗｰです
OS_RET_CODE_INVALID_NAME#~Sep@#Invalid Name#~Sep@#不正な名前です
OS_RET_CODE_CREATE_FAILED#~Sep@#Create operation failed#~Sep@#作成操作が失敗しました
OS_RET_CODE_DEL_DRIVE#~Sep@#Could not delete a drive!#~Sep@#ﾄﾞﾗｲﾌﾞを削除できませんでした
OS_RET_CODE_COPY_SHARED_FILE#~Sep@#Copy file failed. File is use by another process#~Sep@#ﾌｧｲﾙのｺﾋﾟｰに失敗しました。ﾌｧｲﾙが別のﾌﾟﾛｾｽに使われています
OS_RET_CODE_MOVE_FAIL#~Sep@#Move file failed.#~Sep@#ﾌｧｲﾙの移動に失敗しました
OS_RET_CODE_NO_PERMISSION#~Sep@#No permission to perform the operation#~Sep@#指定された操作を行う許可がありません
OS_RET_CODE_WRITE_PERMISSION#~Sep@#No write permission#~Sep@#書き込みを許可されていません
OS_RET_CODE_READ_PERMISSION#~Sep@#No read permission#~Sep@#読み出しを許可されていません
OS_RET_CODE_NULL_PARAM#~Sep@#Error: NULL parameters#~Sep@#ｴﾗｰ：ﾊﾟﾗﾒｰﾀが NULL です
OS_RET_CODE_DST_SRC_EXIST#~Sep@#Destination directory or file exist#~Sep@#書き込み先のﾃﾞｨﾚｸﾄﾘまたはﾌｧｲﾙはすでに存在します
OS_RET_CODE_DST_SRC_NOT_EXIST#~Sep@#Source directory or file does not exist#~Sep@#元のﾃﾞｨﾚｸﾄﾘまたはﾌｧｲﾙが存在しません
OS_RET_CODE_NO_SPACE#~Sep@#No space left on device#~Sep@#ﾃﾞﾊﾞｲｽに空き領域がありません
OS_RET_CODE_DIFFERENT_DEVICE#~Sep@#Operation on different devices#~Sep@#別のﾃﾞﾊﾞｲｽを対象に操作をしました
OS_RET_CODE_MALLOC_FAIL#~Sep@#Memory allocation failed#~Sep@#ﾒﾓﾘの割り当てに失敗しました
OS_RET_CODE_INVALID_ENCODED_METHOOD#~Sep@#Unmechanized encoded method#~Sep@#ｴﾝｺｰﾄﾞ方式が不明です
OS_RET_CODE_NO_STR_FILE#~Sep@#Can not find strings file#~Sep@#文字列ﾌｧｲﾙが見つかりません
OS_RET_CODE_OPEN_STR_FILE_FAIL#~Sep@#Cannot open strings file#~Sep@#文字列ﾌｧｲﾙを開けません
OS_RET_CODE_READ_STR_FILE_FAIL#~Sep@#Cannot read strings file#~Sep@#文字列ﾌｧｲﾙが読めません
OS_RET_CODE_MALLOC_STR_FILE_FAIL#~Sep@#Cannot allocate memory for strings array#~Sep@#文字列配列のためのﾒﾓﾘ領域が確保できません
OS_RET_CODE_STR_TRUNCATED#~Sep@#String truncated#~Sep@#文字列を切り捨てました
OS_RET_CODE_FAILED_IN_DETECTION#~Sep@#Cannot detect encoding method#~Sep@#ｴﾝｺｰﾄﾞ方式を検出できません
OS_RET_CODE_EUC_OR_SJIS#~Sep@#Encoding method is either EUC or SJIS#~Sep@#ｴﾝｺｰﾄﾞ方式は EUC または SJIS です
OS_RET_CODE_MSG_FILE_TOO_BIG#~Sep@#Strings file is too big#~Sep@#文字列ﾌｧｲﾙが大きすぎます
OS_RET_CODE_CORRUPTED_REQUESTED_FILE#~Sep@#The input massage file format is not valid#~Sep@#入力ﾒｯｾｰｼﾞ・ﾌｧｲﾙの形式が不正です
OS_RET_CODE_FAILED_IN_ENCODED#~Sep@#The conversion operation failed#~Sep@#変換処理に失敗しました
IDS_WINEXEC_OUT_OF_MEM#~Sep@#System was out of memory, or the executable file was corrupt.#~Sep@#ｼｽﾃﾑのﾒﾓﾘ不足か、実行ﾌｧｲﾙが壊れています。
IDS_WINEXEC_FILE_NOT_FOUND#~Sep@#The executable, or one of its components was not found.#~Sep@#実行ﾌｧｲﾙまたはそのｺﾝﾎﾟｰﾈﾝﾄの１つが見つかりませんでした。
IDS_WINEXEC_PATH_NOT_FOUND#~Sep@#Path was not found.#~Sep@#ﾊﾟｽが見つかりませんでした。
IDS_WINEXEC_PROTECTION#~Sep@#Sharing or network-protection error, or a dynamic link to a task.#~Sep@#共有ｴﾗｰ、ﾈｯﾄﾜｰｸ保護ｴﾗｰ、または、ﾀｽｸへの動的なﾘﾝｸです。
IDS_WINEXEC_SEP_DATA_SEG#~Sep@#Library required separate data segments for each task.#~Sep@#ﾗｲﾌﾞﾗﾘは各ﾀｽｸについて個別のﾃﾞｰﾀ・ｾｸﾞﾒﾝﾄを必要としました。
IDS_WINEXEC_INSUFFICIENT_MEM#~Sep@#There was insufficient memory to start the application.#~Sep@#ｱﾌﾟﾘｹｰｼｮﾝを起動するためのﾒﾓﾘが足りませんでした。
IDS_WINEXEC_WINVER_INCORRECT#~Sep@#Windows version was incorrect.#~Sep@#Windows のﾊﾞｰｼﾞｮﾝが正しくありません。
IDS_WINEXEC_EXECUTABLE_INVALID#~Sep@#Executable file was invalid.#~Sep@#実行ﾌｧｲﾙが不正です。
IDS_WINEXEC_OS_MISMATCH#~Sep@#Application was designed for a different operating system.#~Sep@#ｱﾌﾟﾘｹｰｼｮﾝは別のｵﾍﾟﾚｰﾃｨﾝｸﾞ･ｼｽﾃﾑ向けに設計されています。
IDS_WINEXEC_MSDOS4#~Sep@#Application was designed for MS-DOS 4.0.#~Sep@#ｱﾌﾟﾘｹｰｼｮﾝは MS-DOS 4.0 向けに設計されています。
IDS_WINEXEC_UNKNOWN_TYPE#~Sep@#Type of executable file was unknown.#~Sep@#実行ﾌｧｲﾙの種類が不明です。
IDS_WINEXEC_REAL_MODE#~Sep@#Attempt was made to load a real-mode application.#~Sep@#ﾘｱﾙ・ﾓｰﾄﾞ・ｱﾌﾟﾘｹｰｼｮﾝをﾛｰﾄﾞしようとしました。
IDS_WINEXEC_SECOND_INSTANCE#~Sep@#A previous instance of this program is already running.#~Sep@#このﾌﾟﾛｸﾞﾗﾑの以前のﾊﾞｰｼﾞｮﾝがすでに実行中です。
IDS_WINEXEC_COMPRESSED#~Sep@#Cannot load a compressed executable file.#~Sep@#圧縮されている実行ﾌｧｲﾙをﾛｰﾄﾞできません
IDS_WINEXEC_CORRUPT#~Sep@#One of the DLLs required to run this application was corrupt.#~Sep@#このｱﾌﾟﾘｹｰｼｮﾝを実行するために必要な DLL の１つが壊れていました。
IDS_WINEXEC_32BIT#~Sep@#Application requires Microsoft Windows 32-bit extensions.#~Sep@#ｱﾌﾟﾘｹｰｼｮﾝは、Microsoft Windows 32 ﾋﾞｯﾄ拡張機能が必要です。
IDS_WINEXEC_OTHER#~Sep@#Unmechanized WinExec() error %1#~Sep@#不明な WinExec() ｴﾗｰ %1 です
IDS_WINEXEC_LONG_COMMADLINE#~Sep@#Command line to WinExec is to long.#~Sep@#WinExec に対するｺﾏﾝﾄﾞﾗｲﾝが長すぎます。
IDS_WINEXEC_EMPTY_COMMAND#~Sep@#Empty command line for WinExec.#~Sep@#WinExec に対して空のｺﾏﾝﾄﾞﾗｲﾝを渡しています。
IDS_SE_ERR_ASSOCINCOMPLETE#~Sep@#The file name association is incomplete or invalid#~Sep@#ﾌｧｲﾙ名の関連付けが不完全か無効です。
IDS_SE_ERR_DDEBUSY#~Sep@#The DDE transaction could not be completed because other DDE transactions were being processed.#~Sep@#他の DDE ﾄﾗﾝｻﾞｸｼｮﾝが処理中だったため、DDE ﾄﾗﾝｻﾞｸｼｮﾝを完了できませんでした。
IDS_SE_ERR_DDEFAIL#~Sep@#The DDE transaction failed.#~Sep@#DDE ﾄﾗﾝｻﾞｸｼｮﾝが失敗しました。
IDS_SE_ERR_DDETIMEOUT#~Sep@#The DDE transaction could not be completed because the request timed out.#~Sep@#ﾘｸｴｽﾄがﾀｲﾑｱｳﾄしたため、DDE ﾄﾗﾝｻﾞｸｼｮﾝを完了できませんでした。
IDS_SE_ERR_NOASSOC#~Sep@#There is no application associated with the given filename extension.#~Sep@#指定されたﾌｧｲﾙ名拡張子に関連付けられているｱﾌﾟﾘｹｰｼｮﾝはありません。
IDS_SE_ERR_SHARE#~Sep@#A sharing violation occurred.#~Sep@#共有違反が発生しました。
OS_RET_CODE_STRING_FILE_IS_TOO_LONG#~Sep@#The requested message file name is too long.#~Sep@#The requested message file name is too long.#~Sep@#要求されたﾒｯｾｰｼﾞ･ﾌｧｲﾙ名は長すぎます。
OS_RET_CODE_OVERLAP_BASES#~Sep@#Corrupted message file %1. The #BASE lines in the message file is overlapped.#~Sep@#ﾒｯｾｰｼﾞ･ﾌｧｲﾙ %1 は壊れています。ﾒｯｾｰｼﾞ･ﾌｧｲﾙの #BASE 行が重複します。
OS_RET_CODE_BAD_EYECAT#~Sep@#Bad Eye Cat.#~Sep@#Bad Eye Cat.
OS_RET_CODE_INTERR_BASE_GROUP#~Sep@#Corrupted base group structure.#~Sep@#基本ｸﾞﾙｰﾌﾟ構造が壊れています。
OS_RET_CODE_INVALID_MESSAGE_FILE_VERSION#~Sep@#Wrong message file version %1.#~Sep@#ﾒｯｾｰｼﾞ･ﾌｧｲﾙのﾊﾞｰｼﾞｮﾝ（%1）が正しくありません。
OS_RET_CODE_MESSAGE_ID_NOT_FOUND#~Sep@#Cannot find message string for message id number %1.#~Sep@#ﾒｯｾｰｼﾞID番号 %1 に対応するﾒｯｾｰｼﾞ文字列が見つかりません。
OS_RET_CODE_UNSUFFICIENT_PARAMS#~Sep@#The requested parameter number exceeds the limit.#~Sep@#要求されたﾊﾟﾗﾒｰﾀの数が上限を超えています。
OS_RET_CODE_UNSUPPORTED_LANG#~Sep@#Message file in the following language %1 is not supported.#~Sep@#次の言語のﾒｯｾｰｼﾞ･ﾌｧｲﾙはｻﾎﾟｰﾄされていません：%1。
OS_RET_CODE_LINE_TRUNCATED#~Sep@#Corrupted message file %1. A message line has been truncated.#~Sep@#ﾒｯｾｰｼﾞ･ﾌｧｲﾙ %1 は壊れています。ﾒｯｾｰｼﾞ行が切り詰められました。
OS_RET_CODE_MISSING_EQUALS_SIGN#~Sep@#Corrupted message file %1. missing equal sign in the line.#~Sep@#ﾒｯｾｰｼﾞ･ﾌｧｲﾙ %1 は壊れています。行中に等号がありません。
OS_RET_CODE_INVALID_BASE#~Sep@#Corrupted message file %1. Invalid #BASE line.#~Sep@#ﾒｯｾｰｼﾞ･ﾌｧｲﾙ %1 は壊れています。#BASE 行が不正です。
OS_RET_CODE_INVALID_CONTROL_LINE#~Sep@#Corrupted message file %1. Invalid control line.#~Sep@#ﾒｯｾｰｼﾞ･ﾌｧｲﾙが壊れています。制御行が不正です。
OS_RET_CODE_INTERR_INVALID_PARAM#~Sep@#Invalid parameter.#~Sep@#ﾊﾟﾗﾒｰﾀが不正です。
OS_RET_CODE_UNSUPPORTED_OPTION#~Sep@#Unsupported option.#~Sep@#ｻﾎﾟｰﾄされていないｵﾌﾟｼｮﾝです。
OS_RET_CODE_MESSAGE_ID_MISMATCH#~Sep@#Mismatch in requested message id name.#~Sep@#要求されたﾒｯｾｰｼﾞID名のﾐｽﾏｯﾁです。
OS_RET_CODE_FILE_IS_NOT_EXIST#~Sep@#The requested file does not exist.#~Sep@#要求されたﾌｧｲﾙは存在しません。
OS_RET_CODE_IDENTIFIER_LENGTH#~Sep@#Error: identifier too long#~Sep@#ｴﾗｰ：識別子が長すぎます。
OS_RET_CODE_IDENTIFIER_CHAR#~Sep@#Invalid identifier character: identifier character must be alphanumeric or underscore.#~Sep@#識別子の文字が不正です。識別子で使える文字は、英数字とｱﾝﾀﾞｰｽｺｱです。
OS_RET_CODE_IDENTIFIER_FIRST_CHAR#~Sep@#Invalid identifier: first character must be a letter or underscore#~Sep@#識別子が不正です。先頭の文字は英字またはｱﾝﾀﾞｰｽｺｱでなければなりません。
OS_RET_CODE_OUT_OF_PARAM_RANGE#~Sep@#Corrupted error string, one of the parameters in out of max param range.#~Sep@#ｴﾗｰ列は不正です。一つのﾊﾟﾗﾒｰﾀは範囲を超えています。
OS_RET_CODE_MSG_NOT_SET#~Sep@#Message not set by os_format_msg. Call customer service #~Sep@#ﾒｯｾｰｼﾞは os_format_msg により設定されていません。お客様ｻｰﾋﾞｽにご連絡下さい。
OS_RET_CODE_INVALID_VALUE#~Sep@#Invalid value#~Sep@#Invalid value
OS_RET_CODE_VALUE_TOO_LARGE#~Sep@#Value too large#~Sep@#Value too large
OS_RET_CODE_PARAM_TOO_LONG#~Sep@#A parameter is too long#~Sep@#A parameter is too long
OS_RET_CODE_TOO_MANY_PARAMS#~Sep@#Too many parameters in the command line#~Sep@#Too many parameters in the command line
OS_RET_CODE_INVALID_QUOTE#~Sep@#Unmatched quotes#~Sep@#Unmatched quotes
