%% HRL file generated by ERLSOM
%%
%% It is possible to change the name of the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.

-record('cwmp:ValueChangeResponse', {anyAttribs, 'MaxEnvelopes'}).
-record('cwmp:BootResponse', {anyAttribs, 'MaxEnvelopes'}).
-record('cwmp:ValueChange', {anyAttribs, 'DeviceId', 'Ip', 'MaxEnvelopes', 'CurrentTime', 'RetryCount', 'ParameterList'}).
-record('cwmp:Boot', {anyAttribs, 'DeviceId', 'Ip', 'MaxEnvelopes', 'CurrentTime', 'RetryCount'}).


-record('cwmp:GetParameterAttributesResponse', {anyAttribs, 'ParameterList'}).
-record('cwmp:GetParameterAttributes', {anyAttribs, 'DeviceId', 'Ip', 'ParameterNames'}).
-record('cwmp:SetParameterAttributesResponse', {anyAttribs}).
-record('cwmp:SetParameterAttributes', {anyAttribs, 'DeviceId', 'Ip', 'ParameterList'}).
-record('cwmp:GetParameterValuesResponse', {anyAttribs, 'ParameterList'}).
-record('cwmp:GetParameterValues', {anyAttribs, 'DeviceId', 'Ip', 'ParameterNames'}).
-record('cwmp:SetParameterValuesResponse', {anyAttribs, 'Status'}).
-record('cwmp:SetParameterValues', {anyAttribs, 'DeviceId', 'Ip', 'ParameterList', 'ParameterKey'}).




-record('cwmp:XFileEvent', {anyAttribs, 'DeviceId', 'Event', 'OUI'}).
-record('cwmp:XFileEventResponse', {anyAttribs}).

-record('cwmp:MonitorGetParameterAttributes', {anyAttribs, 'DeviceId', 'Ip', 'ParameterNames'}).
-record('cwmp:MonitorSetParameterAttributes', {anyAttribs, 'DeviceId', 'Ip', 'ParameterList'}).
-record('cwmp:MonitorGetParameterValues', {anyAttribs, 'DeviceId', 'Ip', 'ParameterNames'}).
-record('cwmp:MonitorSetParameterValues', {anyAttribs, 'DeviceId', 'Ip', 'ParameterList', 'ParameterKey'}).

-record('cwmp:ParameterAttributeList', {anyAttribs, 'P:offset', 'P:arrayType', 'href', 'id', 'ParameterAttributeStruct'}).
-record('cwmp:ParameterAttributeStruct', {anyAttribs, 'Name', 'Notification', 'AccessList'}).
-record('cwmp:SetParameterAttributesList', {anyAttribs, 'P:offset', 'P:arrayType', 'href', 'id', 'SetParameterAttributesStruct'}).
-record('cwmp:SetParameterAttributesStruct', {anyAttribs, 'Name', 'NotificationChange', 'Notification', 'AccessListChange', 'AccessList'}).
-record('cwmp:AccessList', {anyAttribs, 'P:offset', 'P:arrayType', 'href', 'id', 'string'}).
-record('cwmp:ParameterNames', {anyAttribs, 'P:offset', 'P:arrayType', 'href', 'id', 'string'}).
-record('cwmp:ParameterInfoList', {anyAttribs, 'P:offset', 'P:arrayType', 'href', 'id', 'ParameterInfoStruct'}).
-record('cwmp:ParameterInfoStruct', {anyAttribs, 'Name', 'Writable'}).
-record('cwmp:ParameterValueList', {anyAttribs, 'P:offset', 'P:arrayType', 'href', 'id', 'ParameterValueStruct'}).
-record('cwmp:ParameterValueStruct', {anyAttribs, 'Name', 'Value'}).
-record('cwmp:EventList', {anyAttribs, 'P:offset', 'P:arrayType', 'href', 'id', 'EventStruct'}).
-record('cwmp:EventStruct', {anyAttribs, 'EventCode', 'CommandKey'}).
-record('cwmp:DeviceIdStruct', {anyAttribs, 'Manufacturer', 'OUI', 'ProductClass', 'SerialNumber'}).

-record('P:detail', {anyAttribs, choice}).
-record('P:Fault', {anyAttribs, 'faultcode', 'faultstring', 'faultactor', 'detail'}).
-record('P:Body', {anyAttribs, choice}).
-record('soap:Header', {anyAttribs, choice}).
-record('P:Envelope', {anyAttribs, 'Header', 'Body', choice}).
-record('P:Array', {anyAttribs, 'P:offset', 'P:arrayType', 'href', 'id', choice}).
-record('P:Struct', {anyAttribs, 'href', 'id', choice}).
-record('P:duration', {anyAttribs, 'href', 'id', '#text'}).
-record('P:dateTime', {anyAttribs, 'href', 'id', '#text'}).
-record('P:NOTATION', {anyAttribs, 'href', 'id', '#text'}).
-record('P:time', {anyAttribs, 'href', 'id', '#text'}).
-record('P:date', {anyAttribs, 'href', 'id', '#text'}).
-record('P:gYearMonth', {anyAttribs, 'href', 'id', '#text'}).
-record('P:gYear', {anyAttribs, 'href', 'id', '#text'}).
-record('P:gMonthDay', {anyAttribs, 'href', 'id', '#text'}).
-record('P:gDay', {anyAttribs, 'href', 'id', '#text'}).
-record('P:gMonth', {anyAttribs, 'href', 'id', '#text'}).
-record('P:boolean', {anyAttribs, 'href', 'id', '#text'}).
-record('P:base64Binary', {anyAttribs, 'href', 'id', '#text'}).
-record('P:hexBinary', {anyAttribs, 'href', 'id', '#text'}).
-record('P:float', {anyAttribs, 'href', 'id', '#text'}).
-record('P:double', {anyAttribs, 'href', 'id', '#text'}).
-record('P:anyURI', {anyAttribs, 'href', 'id', '#text'}).
-record('P:QName', {anyAttribs, 'href', 'id', '#text'}).
-record('P:string', {anyAttribs, 'href', 'id', '#text'}).
-record('P:normalizedString', {anyAttribs, 'href', 'id', '#text'}).
-record('P:token', {anyAttribs, 'href', 'id', '#text'}).
-record('P:language', {anyAttribs, 'href', 'id', '#text'}).
-record('P:Name', {anyAttribs, 'href', 'id', '#text'}).
-record('P:NMTOKEN', {anyAttribs, 'href', 'id', '#text'}).
-record('P:NCName', {anyAttribs, 'href', 'id', '#text'}).
-record('P:NMTOKENS', {anyAttribs, 'href', 'id', '#text'}).
-record('P:ID', {anyAttribs, 'href', 'id', '#text'}).
-record('P:IDREF', {anyAttribs, 'href', 'id', '#text'}).
-record('P:ENTITY', {anyAttribs, 'href', 'id', '#text'}).
-record('P:IDREFS', {anyAttribs, 'href', 'id', '#text'}).
-record('P:ENTITIES', {anyAttribs, 'href', 'id', '#text'}).
-record('P:decimal', {anyAttribs, 'href', 'id', '#text'}).
-record('P:integer', {anyAttribs, 'href', 'id', '#text'}).
-record('P:nonPositiveInteger', {anyAttribs, 'href', 'id', '#text'}).
-record('P:negativeInteger', {anyAttribs, 'href', 'id', '#text'}).
-record('P:long', {anyAttribs, 'href', 'id', '#text'}).
-record('P:int', {anyAttribs, 'href', 'id', '#text'}).
-record('P:short', {anyAttribs, 'href', 'id', '#text'}).
-record('P:byte', {anyAttribs, 'href', 'id', '#text'}).
-record('P:nonNegativeInteger', {anyAttribs, 'href', 'id', '#text'}).
-record('P:unsignedLong', {anyAttribs, 'href', 'id', '#text'}).
-record('P:unsignedInt', {anyAttribs, 'href', 'id', '#text'}).
-record('P:unsignedShort', {anyAttribs, 'href', 'id', '#text'}).
-record('P:unsignedByte', {anyAttribs, 'href', 'id', '#text'}).
-record('P:positiveInteger', {anyAttribs, 'href', 'id', '#text'}).
-record('P:anyType', {anyAttribs, choice}).
