%% Author: bin.liu
%% Created: 2009-9-22
%% Description: report object 
 -record(report,{id="",
				 email = "",
				 name="",
                 emailData = "",
                 xmlEmailData = "",
                 reportTitle = "",
                 mailTemplate = "",
                 queryID = "",
                 portalQuery = "",
                 title = "History",
				 description = "",
				 disabledChecked = "",
				 detailedChecked = "",
				 attachReportChecked = "",
				 tabfileChecked = "",
				 xmlfileChecked = "",
				 bestCaseCalcChecked = "",
				 statusFilter = "",
				 schedFilter = "",
				 operation = "adhoc",
				 page = "report",
				 operationString = "Show Quick",
				 helpFile = "",
				 errors = "",
				 hiddenQueryID = "",
				 hoursOptions = "",
				 minutesOptions = "",
				 windowsOptions = "",
				 precisionOptions = "",
				 formatOptions = "",
				 vmaxOptions = "",
				 startHourOptions = "",
				 startTimeHTML = "",
				 endTimeHTML = "",
				 monitorOptionsHTML = "",
				 reportTypeHTML = "",
				 scheduleHour = 1,
				 scheduleMinute = 0,
				 readOnly = false
				}).

        
