package com.dragonflow.siteview.exchange;

import java.io.File;

import com.dragonflow.siteview.infra.util.ServicePlatform;

public class ExchConstants {
	public static final String PARAM_PS_CONSOLE_FILE = "$PS_CONSOLE_FILE$";
	   public static final String PARAM_SERVER = "$SERVER$";
	   public static final String PARAM_SCRIPTT = "$SCRIPT$";
	   public static final String PARAM_ACCOUNT = "$ACCOUNT$";
	   public static final String PARAM_DC = "$DOMAIN_CONTROLLER$";
	   public static final String PARAM_COMMAND = "$COMMAND$";
	   public static final String SPACE_DEL = "SPACE";
	   public static final String PS_CONSOLE_FILE_SUFFIX = ".psc1";
	   public static final String NO_MEASUREMENT = "n/a";
	   public static final String TEST_CMDLETS_SCRIPT_PATH =ServicePlatform.getRoot()+ File.separator+"templates.applications"+File.separator+"scripts.exchange2007"+File.separator+"ExchangeTestCmdlets.ps1" ;
	  // public static final String GET_EXCHANGE_SCRIPT_PATH = ServicePlatform.getRoot() + File.separator + "templates.applications" + File.separator + "scripts.exchange2007" + File.separator + "GetExchangeServer.ps1";
	   public static final String GET_EXCHANGE_SCRIPT_PATH = ServicePlatform.getRoot() +  "/templates.applications/scripts.exchange2007/GetExchangeServer.ps1";
	   public static final String COUNTER_DELIMITER = "/";
	   public static final String OUTPUT_DELIMITER = ":";
	   public static final String OUTPUT_DELIMITER_REGEX = "\\s+:\\s+";
	   public static final String TITEL_OUTPUT_REGEX = "---\\s+.*\\s+---";
	   public static final String ERROR_REGEX_1 = "\\+.*<<<<.*";
	   public static final String ERROR_REGEX_2 = ".*<<<<.*";
	   public static final String ERROR_REGEX_3 = "At\\s+.*:\\d+\\s+.*:\\d+";
	   public static final String TRUE = "True";
	   public static final String TRUE_PARAM = "$true";
	   public static final String FALSE = "False";
	   public static final String FALSE_PARAM = "$false";
	   public static final String SPACE = " ";
	   public static final String EXPR = "---";
	   public static final int DEFAULT_FREQUENCY = 600;
	   public static final int DEFAULT_TIMEOUT = 120;
	   public static final int MIN_TIMEOUT = 1;
	   public static final int MAX_TIMEOUT = 600;
	   public static final String GET_EXCAHNGESERVER_TITEL = "--- GET-EXCHANGESERVER_OUTPUT ---";
	   public static final String TEST_MAPICONNECTIVITY_TITEL = "--- TEST-MAPICONNECTIVITY_OUTPUT ---";
	   public static final String TEST_MAILFLOW_TITEL = "--- TEST-MAILFLOW_OUTPUT ---";
	   public static final String TEST_EXCHANGESEARCH_TITEL = "--- TEST-EXCHANGESEARCH_OUTPUT ---";
	   public static final String TEST_OWACONNECTIVITY_TITEL = "--- TEST-OWACONNECTIVITY_OUTPUT ---";
	   public static final String TEST_WEBSERVICESCONNECTIVITY_TITEL = "--- TEST-WEBSERVICESCONNECTIVITY_OUTPUT ---";
	   public static final String IS_MAILBOX_SERVER = "IsMailboxServer";
	   public static final String IS_CLIENT_ACCESS_SERVER = "IsClientAccessServer";
	   public static final String IS_UNIFIED_MESSAGING_SERVER = "IsUnifiedMessagingServer";
	   public static final String IS_HUB_TRANSPORT_SERVER = "IsHubTransportServer";
	   public static final String IS_EDGE_SERVER = "IsEdgeServer";
	   public static final String LABEL_EXCHANGESERVER = "Get-ExchangeServer";
	   public static final String LABEL_MAPICONNECTIVITY = "MAPI Connectivity";
	   public static final String LABEL_MAPICONNECTIVITY_DESC = "Testing MAPI Connectivity using Test-MAPIConnectivity cmdlet";
	   public static final String LABEL_MAPICONNECTIVITYRESULT_DESC = "MAPI Connectivity test result";
	   public static final String LABEL_MAPICONNECTIVITYLATENCY_DESC = "MAPI Connectivity test latency";
	   public static final String LABEL_MAILFLOW = "Mail Flow";
	   public static final String LABEL_MAILFLOWRESULT = "TestMailflowResult";
	   public static final String LABEL_MESSAGELATENCY = "MessageLatencyTime";
	   public static final String LABEL_MAILFLOW_DESC = "Testing Mail flow using Test-Mailflow cmdlet";
	   public static final String LABEL_MAILFLOWRESULT_DESC = "Mail flow test result";
	   public static final String LABEL_MESSAGELATENCY_DESC = "Mail flow test latency";
	   public static final String LABEL_EXCHANGESEARCH = "Exchange Search";
	   public static final String LABEL_RESULTFOUND = "ResultFound";
	   public static final String LABEL_SEARCHTIME = "SearchTime";
	   public static final String LABEL_EXCHANGESEARCH_DESC = "Testing Exchange Search using Test-ExchangeSearch cmdlet";
	   public static final String LABEL_RESULTFOUND_DESC = "Exchange Search test result";
	   public static final String LABEL_SEARCHTIME_DESC = "Exchange Search test search time";
	   public static final String LABEL_OWACONNECTIVITY = "OWA Connectivity";
	   public static final String LABEL_OWACONNECTIVITY_DESC = "Testing Microsoft Office Outlook Web Access Connectivity using Test-OWAConnectivity cmdlet";
	   public static final String LABEL_OWACONNECTIVITYRESULT_DESC = "Microsoft OWA test result";
	   public static final String LABEL_OWACONNECTIVITYLATENCY_DESC = "Microsoft OWA test latency";
	   public static final String LABEL_WEBSERVICESCONNECTIVITY = "Web Services Connectivity";
	   public static final String LABEL_GETFOLDER_SCENARIO = "GetFolder";
	   public static final String LABEL_SYNCFOLDERITEMS_SCENARIO = "SyncFolderItems";
	   public static final String LABEL_CREATEITEM_SCENARIO = "CreateItem";
	   public static final String LABEL_DELETEITEM_SCENARIO = "DeleteItem";
	   public static final String LABEL_START_SCENARIO_MARK = "ClientAccessServer";
	   public static final String LABEL_WEBSERVICESCONNECTIVITY_DESC = "Testing Exchange Web Services using Test-WebServicesConnectivity cmdlet";
	   public static final String LABEL_GETFOLDER_DESC = "Exchange Web Services Test: GetFolder Scenario";
	   public static final String LABEL_GETFOLDERRESULT_DESC = "Exchange Web Services Test: GetFolder Scenario result";
	   public static final String LABEL_GETFOLDERLATENCY_DESC = "Exchange Web Services Test: GetFolder Scenario latency";
	   public static final String LABEL_SYNCFOLDERITEMS_DESC = "Exchange Web Services Test: SyncFolderItems Scenario";
	   public static final String LABEL_SYNCFOLDERITEMSRESULT_DESC = "Exchange Web Services Test: SyncFolderItems Scenario result";
	   public static final String LABEL_SYNCFOLDERITEMSLATENCY_DESC = "Exchange Web Services Test: SyncFolderItems Scenario latency";
	   public static final String LABEL_CREATEITEM_DESC = "Exchange Web Services Test: CreateItem Scenario";
	   public static final String LABEL_CREATEITEMRESULT_DESC = "Exchange Web Services Test: CreateItem Scenario result";
	   public static final String LABEL_CREATEITEMLATENCY_DESC = "Exchange Web Services Test: CreateItem Scenario latency";
	   public static final String LABEL_DELETEITEM_DESC = "Exchange Web Services Test: DeleteItem Scenario";
	   public static final String LABEL_DELETEITEMRESULT_DESC = "Exchange Web Services Test: DeleteItem Scenario result";
	   public static final String LABEL_DELETEITEMLATENCY_DESC = "Exchange Web Services Test: DeleteItem Scenario latency";
	   public static final String LABEL_RESULT = "Result";
	   public static final String LABEL_LATENCY = "Latency";

}
