%% HRL file generated by ERLSOM
%%
%% It is possible to change the name of the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.

-record('env:UpgradeType', {anyAttribs, 'SupportedEnvelope'}).
-record('env:SupportedEnvType', {anyAttribs, 'qname'}).
-record('env:NotUnderstoodType', {anyAttribs, 'qname'}).
-record('env:detail', {anyAttribs, choice}).
-record('env:subcode', {anyAttribs, 'Value', 'Subcode'}).
-record('env:faultcode', {anyAttribs, 'Value', 'Subcode'}).
-record('env:reasontext', {anyAttribs, 'xml:lang', '#text'}).
-record('env:faultreason', {anyAttribs, 'Text'}).
-record('env:Fault', {anyAttribs, 'Code', 'Reason', 'Node', 'Role', 'Detail'}).
-record('env:Body', {anyAttribs, choice}).
-record('env:Header', {anyAttribs, choice}).
-record('env:Envelope', {anyAttribs, 'Header', 'Body'}).
